# Configuration
baseURL = ''
languageCode = 'fr'
defaultContentLanguage = 'fr'
title = 'SCP~37'

[params]
    titreBanniere = "Bienvenue sur le site de la SCP~37"
    descriptionBanniere = "Association d'informatique basée à l'université de Tours."
    logoDefaut = "media/assoLogo.png"
    logoBanniere = "media/blason.png"

# liste toutes les pages
sectionPagesMenu = "toutesLesPages"

# Menus
[menu]
    [[menu.main]]
    name = '/home'
    weight = 10
    pageRef = '/'
    [[menu.main]]
    name = '/events'
    weight = 20
    pageRef = '/events'
    [[menu.main]]
    name = '/conseil'
    pageRef = '/membres'
    weight = 30
    pageRef = '/historique'
    weight = 40'
    [[menu.main]]
    name = '/infos'
    weight = 50
    pageRef = '/infos'

    [[menu.shortcuts]]
        name = "<i class='fa-brands fa-discord fa-xl'></i>"
        url = ""
        weight = 1
        title = "Découvez notre discord!"
    [[menu.shortcuts]]
        name = "<i class='fab fa-instagram fa-xl'></i>"
        url = ""
        weight = 2
        title = "Suivez-nous sur Instagram!"
    [[menu.shortcuts]]
        name = "<img class='helloAssoLogo' src='media/helloAssoLogo.png'>"
        url = "https://www.helloasso.com/associations/societe-chevaleresque-des-programmeurs-37/adhesions/adhesion-2023-2024"
        weight = 3
        title = "Rejoignez l'asso!"


    [[menu.footer]]
        name = "règlement"
        pageRef = "/reglement"
        weight = 1

    [[menu.footer]]
        name = "charte"
        pageRef = "/charte"
        weight = 1